### ISSUE TITLE
Meeting 6/15?16?

### ISSUE THREAD

**Issue by WilliamJizh** [JimmyRowland/team_sporty#12]
1.Workflow discussion
2.How should we making components
3.Start backend implementation

**Comment by JimmyRowland** [comment]
I will be able to pick up some speed after Jun 24. 
And I will follow this tutorial to set up the backend

https://www.youtube.com/watch?v=Y0lDGjwRYKw&list=PL4cUxeGkcC9iK6Qhn-QLcXCXPQUov1U7f
https://www.youtube.com/watch?v=SEMTj8w04Z8&list=PLillGF-RfqbZrjw48EXLdM4dsOhURCLZx
