### ISSUE TITLE
Scrum Update 3

### ISSUE THREAD

**Issue by engineereng** [JimmyRowland/team_sporty#17]
1. I spent some time looking over the code base and trying to figure out how we would implement some of the actions.
2. I found myself very busy with other commitments this sprint and unable to focus on the project.
3. For the next sprint, I will focus on finishing the other components and setting up the database. I plan to make a lot of progress for the next sprint.
i5m1b

**Comment by JimmyRowland** [comment]
1. I wrote some reducers to pull data from a place holder API.
2. I fixed the issue where route change would lead to state reset, but I couldn't get the route transition working without losing state.
3. I will try to migrate the frontend to use next.js and apollo. 

t4y2b

**Comment by gparappilly** [comment]
1. This past iteration, I fixed some of the appearance aspect for certain features, and also started on the Calendar Page.
2. I'm still getting used to Material UI, but other than that, no real issues.
3. For the upcoming iteration, I plan to finalize the look of the calendar page, fix design flaws with other parts, set up more actions, and hopefully contribute to integrating the user authentication and database connection with our site.

n1u9a

**Comment by WilliamJizh** [comment]
1. I implemented the reducers for editing personal profiles and posting posts.
2. I felt quite challenging to keep adapting new techs, but with some time spent I was able to comprehend them alright.
3. For the next sprint, I'll look into the backend techs we're going to use and hopefully help to fulfill all of our minimum goals ASAP.

v2u1b
