### ISSUE TITLE
Scrum update 5

### ISSUE THREAD

**Issue by engineereng** [JimmyRowland/team_sporty#25]
1. I learned GraphQL and Apollo at a working level and am working on fixing bugs, implementing teams, and cleaning up code and documentation for our final presentation.
2. I found the transition to GraphQL and Apollo difficult, and I am only now understanding how to contribute meaningfully to the project.
3. I will finish up our team page and polish our project for the presentation.
i5m1b

**Comment by JimmyRowland** [comment]
1. I set up the setting page, wrote some resolvers, and deployed the app on vercel and heroku.
2. Types generated by graphql generator are very difficult to work with and it took a lot of time to fix all the type errors to deploy the app on vercel.
3. I will try to fix all the type errors and implement lazy loading.

**Comment by WilliamJizh** [comment]
1. I implemented several frontend features and styled some components during this sprint.
2. Styling components efficiently is quite challenging, but I've picked up in speed with the experience accumulated.
3. I'll keep working on more features and help to fulfill more goals.
v2u1b

**Comment by gparappilly** [comment]
1. I mainly worked on front end components and styling such as the UI for the calendar page, and some components on the profile and team pages. Also worked to fix some bugs and errors.
2. Major issues were dealing with some of the backend stuff. It took some time to finally understand Apollo and GraphQL.
3. For this next iteration, I plan to hopefully finish a lot of the styling, clean up unnecessary code, help with the documentation, and fix many of the warnings/errors.
