### ISSUE TITLE
Scrum Update 2

### ISSUE THREAD

**Issue by JimmyRowland** [JimmyRowland/team_sporty#8]
1. I set up the frontend structure, built the eventList component, and flexboxes for the team page and the personal page.
2. I am really bad at design. Couldn't make the UI appealing. Gathering necessary packages is difficult.
3. I will polish the existing components.
t4y2b

**Comment by gparappilly** [comment]
1.  This past iteration, I helped contribute to project discussion and also created the components for TeamItem and TeamList. 

2. One of the major challenges I find is the fact that its still kind of hard to explain thought processes without seeing each other in person. As well, I found my lack of familiarity with React and Material UI to be an obstacle.

3. I plan to be more familiar with Redux and Material UI so I can be more efficient and effective when working on the project and and contribute more time to working on other features/components.

**Comment by WilliamJizh** [comment]
1. I contributed to establish the visual design of our application and worked on the personal info tab component.

2. I still lack some crucial knowledge about react and redux, so I felt implementing components correctly and efficiently was quite challenging.

3. I'll keep work on creating more components while connecting the current components I made with redux. At the same time, I will try to get more familiar with the material UI kit to help the visual presentation.

**Comment by engineereng** [comment]
1. I participated in establishing the visual design of our application and organizing deadlines.
2. I struggled a lot with React and Redux and was not able to complete my assigned components.
3. I will continue to help the team organize deadlines and a timeline, and I will invest a significant amount of time in learning React and Redux so I can contribute for the next sprint.
i5m1b

**Comment by dustxd** [comment]
@gparappilly Remember to include your CSID next time! :)
